### ISSUE TITLE
LastException when Sim with changed pronouns gets a job

### ISSUE THREAD

**Issue by TheWorldsAddress** [NeonOcean/S4.Refer#2]
I get a LastException error when I change pronouns with the Refer mod and then have my Sim get a job.
The way I can reproduce the error is:
1. Copy the Refer and Main mod into the mod folder
2. Start the game and create a new Sim
3. Place the Sim in a random house
4. Select the Sim and change the pronouns with the Refer mod.
5. Use the phone to get the Sim a job. Pick a rabbithole job, like astronaut, athlete or culinary. The error may not happen with the active carreers.
6. A LE is now generated and the job notification uses the Sim's original pronouns, not the pronouns selected in Refer.

When the Sims gains a skill, the notification works correctly, with the pronouns selected in Refer.
I'm using the 64bit version of the Sims with the latest patch (1.69.59.1020) and Main mod version 2.2.0 and Refer version 1.1.0. I also tried Refer version 1.0.1 with the same results. I've tested the above with no other mods than Main and Refer.
[CollectedData.zip](https://github.com/NeonOcean/S4.Refer/files/5697995/CollectedData.zip)

**Comment by NeonOcean** [comment]
Okay, I've fixed this bug. Hopefully, I'll release the update some time today.
