### ISSUE TITLE
Default pronouns are used for high school student text

### ISSUE THREAD

**Issue by sneedleborp** [NeonOcean/S4.Refer#3]
My sim is a high school student, and when you hover over the high school student icon, a passage of text pops up using their default (she/her) pronouns, even though i have their pronouns set to they/them and fallback set to "male" text.

**Comment by NeonOcean** [comment]
This is a problem with the game. A few snippets of text here and there can't be modified by this mod because it doesn't run through the bit of code I can mess with, sorry.
